// React
import type { Metadata } from 'next';

// Localization
import 'src/locales/i18n';
import LocalizationProvider from '@/locales/localization-provider'

// Settings
import { SettingsProvider } from '@/components/settings'

// Theme 
import ThemeProvider from '@/theme';
import { primaryFont } from '@/theme/typography';

// Authorization
import { AuthProvider } from '@/auth/context/AuthProvider';
import { AuthConsumer } from '@/auth/context/AuthConsumer';
import ProgressBar from '@/components/progress-bar';

export const metadata: Metadata = {
  title: 'Kanban MVP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={primaryFont.className}>
      <body>
        <AuthProvider>
          <LocalizationProvider>
            <SettingsProvider defaultSettings={{ themeMode: 'light' }}>
              <ThemeProvider>
                <ProgressBar />
                <AuthConsumer>
                  {children}
                </AuthConsumer>
              </ThemeProvider>
            </SettingsProvider>
          </LocalizationProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
