// i18n
import 'src/locales/i18n';

import { SettingsProvider } from '@/components/settings'
import type { Metadata } from 'next'
import LocalizationProvider from '@/locales/localization-provider'
import ThemeProvider from '@/theme';
import { primaryFont } from '@/theme/typography';
import { AuthProvider } from '@/auth/context/auth-provider';
import { AuthConsumer } from '@/auth/context/auth-consumer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={primaryFont.className}>
      <body>
        <AuthProvider>
          <LocalizationProvider>
            <SettingsProvider defaultSettings={{ themeMode: 'light' }}>
              <ThemeProvider>
                <AuthConsumer>
                  {children}
                </AuthConsumer>
              </ThemeProvider>
            </SettingsProvider>
          </LocalizationProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
